CREATE TABLE SUPPLIER(
  SNO TEXT PRIMARY KEY,
  SAME TEXT,
  STATUS INTEGER,
  CITY TEXT
);

INSERT INTO SUPPLIER (SNO,SAME,STATUS,CITY) VALUES 
   ('S1','SMITH',20,'LONDON'),
   ('S2','SMITH',10,'PARIS'),
   ('S3','JONE',30,'PARIS'),
   ('S4','CLARKE',20,'LONDON'),
   ('S5','JHON',30,'GREECES');

SELECT * FROM SUPPLIER;
  



